import express from 'express';
const router = express.Router();

/**
 * @route   POST /api/nexus/generate
 * @desc    Generate code/content via Nexus AI (SSE Stream)
 */
router.post('/generate', async (req, res) => {
  const { messages, model, projectFiles, agentMode } = req.body;

  // Set SSE Headers
  res.setHeader('Content-Type', 'text/plain; charset=utf-8');
  res.setHeader('Transfer-Encoding', 'chunked');
  res.setHeader('Cache-Control', 'no-cache');
  res.setHeader('Connection', 'keep-alive');

  const lastUserMessage = messages[messages.length - 1]?.content.toLowerCase() || "";

  // Simulated AI response for demo purposes
  let responseText = "";
  
  if (lastUserMessage.includes("hero") || lastUserMessage.includes("landing")) {
    responseText = `I'll create a stunning, responsive hero section for your project. I'm using Framer Motion for animations and Tailwind CSS for the premium dark theme.

<file path='src/components/Hero.jsx' action='create'>
import React from 'react';
import { motion } from 'framer-motion';

export default function Hero() {
  return (
    <section className="relative min-h-screen flex items-center justify-center overflow-hidden bg-[#080810]">
      {/* Background Glow */}
      <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] bg-cyan-500/10 blur-[120px] rounded-full" />
      <div className="absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] bg-purple-600/10 blur-[120px] rounded-full" />
      
      <div className="container mx-auto px-6 relative z-10 text-center">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
        >
          <span className="inline-block px-4 py-1.5 mb-6 text-[10px] font-bold uppercase tracking-widest text-cyan-400 bg-cyan-400/10 border border-cyan-400/20 rounded-full">
            Nexus AI Powering Innovation
          </span>
          <h1 className="text-6xl md:text-8xl font-black text-white mb-8 tracking-tighter leading-none">
            Build the Future <br />
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 via-purple-500 to-cyan-500">
              at the Speed of Thought
            </span>
          </h1>
          <p className="max-w-2xl mx-auto text-lg md:text-xl text-slate-400 mb-10 leading-relaxed font-medium">
            Next-generation AI development workspace. From idea to production 
            in seconds. No limits, only pure creativity.
          </p>
          
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <button className="px-8 py-4 bg-white text-black font-bold rounded-full hover:scale-105 transition-all shadow-[0_20px_40px_rgba(255,255,255,0.1)]">
              Start Building Now
            </button>
            <button className="px-8 py-4 bg-white/5 text-white font-bold rounded-full border border-white/10 hover:bg-white/10 transition-all">
              Watch Demo
            </button>
          </div>
        </motion.div>
      </div>
    </section>
  );
}
</file>

<file path='src/App.jsx' action='modify'>
import React from 'react';
import Hero from './components/Hero';

export default function App() {
  return (
    <div className="min-h-screen">
      <Hero />
    </div>
  );
}
</file>

I have created a new \`Hero.jsx\` component with hardware-accelerated animations 
and updated \`App.jsx\` to render it. The design follows the AlgoForce flagship style.`;
  } else {
    responseText = `Sure, I can help with that. I'm working on the code now...

<file path='src/components/NewFeature.jsx' action='create'>
import React from 'react';

export default function NewFeature() {
  return (
    <div className="p-10 bg-[#0f0f1a] rounded-3xl border border-[#1a1a2e]">
      <h2 className="text-2xl font-bold text-cyan-400">New Feature Core</h2>
      <p className="text-slate-400 mt-2">Autonomously generated by Nexus AI.</p>
    </div>
  );
}
</file>

Done! I've created the component based on your request. Let me know if you want any refinements!`;
  }

  // Stream word by word
  const words = responseText.split(' ');
  for (let i = 0; i < words.length; i++) {
    res.write(words[i] + (i === words.length - 1 ? '' : ' '));
    // Simulate network delay
    await new Promise(r => setTimeout(r, Math.random() * 50 + 20));
  }
  
  res.end();
});

export default router;
